export const chats = [
    {
        user_id: 2,
        messages: [
            {
                id: 1,
                user_id: 2,
                text: 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus',
                timestamp: 1652100188000,
                status: 'read',
            },
            {
                id: 2,
                user_id: 1,
                text: 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis',
                img_attachment: new URL('/static/img/attachments/attch1.jpg', import.meta.url).href,
                timestamp: 1652170143000,
                status: 'read',
            },
            {
                id: 3,
                user_id: 1,
                text: 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel',
                timestamp: 1652163358000,
                status: 'read',
            },
            {
                id: 4,
                user_id: 1,
                text: 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet',
                img_attachment: new URL('/static/img/attachments/attch2.jpg', import.meta.url).href,
                timestamp: 1651374060000,
                status: 'read',
            },
            {
                id: 5,
                user_id: 1,
                text: 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui',
                timestamp: 1651488283000,
                status: 'read',
            },
            {
                id: 6,
                user_id: 1,
                text: 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque',
                timestamp: 1651509432000,
                status: 'read',
            },
            {
                id: 7,
                user_id: 1,
                text: 'orci luctus et ultrices posuere cubilia curae duis faucibus',
                img_attachment: new URL('/static/img/attachments/attch3.jpg', import.meta.url).href,
                timestamp: 1651382820000,
                status: 'read',
            },
            {
                id: 8,
                user_id: 2,
                text: 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus',
                img_attachment: new URL('/static/img/attachments/attch4.jpg', import.meta.url).href,
                timestamp: 1651910772000,
                status: 'read',
            },
            {
                id: 9,
                user_id: 2,
                text: 'quisque arcu libero rutrum ac lobortis vel dapibus at',
                timestamp: 1651755635000,
                status: 'read',
            },
            {
                id: 10,
                user_id: 2,
                text: 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta',
                timestamp: 1651858110000,
                status: 'read',
            },
            {
                id: 11,
                user_id: 1,
                text: 'accumsan tellus nisi',
                timestamp: 1652230876000,
                status: 'read',
            },
            {
                id: 12,
                user_id: 1,
                text: 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus',
                img_attachment: new URL('/static/img/attachments/attch5.jpg', import.meta.url).href,
                timestamp: 1651864558000,
                status: 'read',
            },
            {
                id: 13,
                user_id: 1,
                text: 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio',
                timestamp: 1651833093000,
                status: 'read',
            },
            {
                id: 14,
                user_id: 2,
                text: 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede',
                timestamp: 1651377110000,
                status: 'read',
            },
            {
                id: 15,
                user_id: 2,
                text: 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget',
                timestamp: 1651526917000,
                status: 'read',
            },
            {
                id: 16,
                user_id: 2,
                text: 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien',
                timestamp: 1651462578000,
                status: 'read',
            },
            {
                id: 17,
                user_id: 2,
                text: 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper',
                timestamp: 1651726662000,
                status: 'read',
            },
            {
                id: 18,
                user_id: 2,
                text: 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque',
                timestamp: 1651769133000,
                status: 'read',
            },
            {
                id: 19,
                user_id: 1,
                text: 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus',
                timestamp: 1651782996000,
                status: 'read',
            },
            {
                id: 20,
                user_id: 1,
                text: 'lectus vestibulum quam sapien varius',
                timestamp: 1652046075000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 3,
        messages: [
            {
                id: 21,
                user_id: 3,
                text: 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo',
                timestamp: 1651919817000,
                status: 'read',
            },
            {
                id: 22,
                user_id: 1,
                text: 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia',
                timestamp: 1652330163000,
                status: 'read',
            },
            {
                id: 23,
                user_id: 1,
                text: 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras',
                timestamp: 1651578459000,
                status: 'read',
            },
            {
                id: 24,
                user_id: 3,
                text: 'erat',
                timestamp: 1651618396000,
                status: 'read',
            },
            {
                id: 25,
                user_id: 1,
                text: 'maecenas tincidunt lacus at velit vivamus vel',
                timestamp: 1651907960000,
                status: 'read',
            },
            {
                id: 26,
                user_id: 3,
                text: 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas',
                timestamp: 1652074512000,
                status: 'read',
            },
            {
                id: 27,
                user_id: 3,
                text: 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget',
                timestamp: 1652022709000,
                status: 'read',
            },
            {
                id: 28,
                user_id: 3,
                text: 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem',
                timestamp: 1651591272000,
                status: 'read',
            },
            {
                id: 29,
                user_id: 1,
                text: 'at feugiat non pretium quis lectus suspendisse potenti in eleifend',
                timestamp: 1651870674000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 4,
        messages: [
            {
                id: 30,
                user_id: 1,
                text: 'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla',
                img_attachment: new URL('/static/img/attachments/attch6.jpg', import.meta.url).href,
                timestamp: 1652122734000,
                status: 'read',
            },
            {
                id: 31,
                user_id: 4,
                text: 'maecenas tincidunt lacus at velit vivamus vel',
                timestamp: 1651431345000,
                status: 'read',
            },
            {
                id: 32,
                user_id: 1,
                text: 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis',
                timestamp: 1651664448000,
                status: 'read',
            },
            {
                id: 33,
                user_id: 1,
                text: 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius',
                timestamp: 1652370536000,
                status: 'delivered',
            },
            {
                id: 34,
                user_id: 4,
                text: 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam',
                timestamp: 1651900708000,
                status: 'read',
            },
            {
                id: 35,
                user_id: 4,
                text: 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla',
                timestamp: 1651378779000,
                status: 'read',
            },
            {
                id: 36,
                user_id: 1,
                text: 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti',
                timestamp: 1651987322000,
                status: 'read',
            },
            {
                id: 37,
                user_id: 1,
                text: 'quis orci eget',
                timestamp: 1652242352000,
                status: 'read',
            },
            {
                id: 38,
                user_id: 1,
                text: 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis',
                timestamp: 1651571831000,
                status: 'read',
            },
            {
                id: 39,
                user_id: 4,
                text: 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque',
                timestamp: 1652009894000,
                status: 'read',
            },
            {
                id: 40,
                user_id: 4,
                text: 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet',
                timestamp: 1652310278000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 5,
        messages: [
            {
                id: 41,
                user_id: 1,
                text: 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus',
                timestamp: 1651831651000,
                status: 'read',
            },
            {
                id: 42,
                user_id: 5,
                text: 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent',
                timestamp: 1652319314000,
                status: 'read',
            },
            {
                id: 43,
                user_id: 1,
                text: 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam',
                timestamp: 1652389662000,
                status: 'read',
            },
            {
                id: 44,
                user_id: 1,
                text: 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in',
                timestamp: 1651791077000,
                status: 'read',
            },
            {
                id: 45,
                user_id: 5,
                text: 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a',
                timestamp: 1651652923000,
                status: 'read',
            },
            {
                id: 46,
                user_id: 5,
                text: 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam',
                timestamp: 1652276819000,
                status: 'read',
            },
            {
                id: 47,
                user_id: 5,
                text: 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus',
                img_attachment: new URL('/static/img/attachments/attch7.jpg', import.meta.url).href,
                timestamp: 1652209852000,
                status: 'read',
            },
            {
                id: 48,
                user_id: 1,
                text: 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam',
                timestamp: 1652254318000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 6,
        messages: [
            {
                id: 49,
                user_id: 6,
                text: 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et',
                timestamp: 1652356383000,
                status: 'read',
            },
            {
                id: 50,
                user_id: 6,
                text: 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris',
                timestamp: 1651626764000,
                status: 'read',
            },
            {
                id: 51,
                user_id: 6,
                text: 'blandit mi in porttitor pede justo eu massa donec dapibus duis',
                timestamp: 1651784633000,
                status: 'read',
            },
            {
                id: 52,
                user_id: 1,
                text: 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper',
                timestamp: 1651565738000,
                status: 'read',
            },
            {
                id: 53,
                user_id: 6,
                text: 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel',
                timestamp: 1651719132000,
                status: 'read',
            },
            {
                id: 54,
                user_id: 1,
                text: 'porta volutpat erat quisque erat',
                timestamp: 1652386546000,
                status: 'read',
            },
            {
                id: 55,
                user_id: 6,
                text: 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus',
                timestamp: 1651616231000,
                status: 'read',
            },
            {
                id: 56,
                user_id: 6,
                text: 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu',
                timestamp: 1652280597000,
                status: 'read',
            },
            {
                id: 57,
                user_id: 1,
                text: 'quisque erat eros viverra eget congue eget semper rutrum',
                timestamp: 1651525229000,
                status: 'read',
            },
            {
                id: 58,
                user_id: 6,
                text: 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo',
                timestamp: 1651363993000,
                status: 'read',
            },
            {
                id: 59,
                user_id: 6,
                text: 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt',
                timestamp: 1651900895000,
                status: 'read',
            },
            {
                id: 60,
                user_id: 1,
                text: 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus',
                timestamp: 1651770728000,
                status: 'read',
            },
            {
                id: 61,
                user_id: 6,
                text: 'in quam fringilla rhoncus mauris enim leo',
                timestamp: 1651709650000,
                status: 'read',
            },
            {
                id: 62,
                user_id: 6,
                text: 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat',
                timestamp: 1651753991000,
                status: 'read',
            },
            {
                id: 63,
                user_id: 6,
                text: 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia',
                timestamp: 1651649574000,
                status: 'read',
            },
            {
                id: 64,
                user_id: 1,
                text: 'sociis natoque penatibus et magnis dis',
                timestamp: 1651876368000,
                status: 'read',
            },
            {
                id: 65,
                user_id: 1,
                text: 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet',
                timestamp: 1651680999000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 7,
        messages: [
            {
                id: 66,
                user_id: 1,
                text: 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie',
                timestamp: 1652177518000,
                status: 'read',
            },
            {
                id: 67,
                user_id: 1,
                text: 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis',
                img_attachment: new URL('/static/img/attachments/attch8.jpg', import.meta.url).href,
                timestamp: 1652012184000,
                status: 'read',
            },
            {
                id: 68,
                user_id: 1,
                text: 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor',
                img_attachment: 'Sapien.ppt',
                timestamp: 1651431038000,
                status: 'read',
            },
            {
                id: 69,
                user_id: 7,
                text: 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla',
                img_attachment: 'VivamusVestibulum.txt',
                timestamp: 1652231946000,
                status: 'read',
            },
            {
                id: 70,
                user_id: 7,
                text: 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis',
                img_attachment: 'EuOrciMauris.mov',
                timestamp: 1651872886000,
                status: 'read',
            },
            {
                id: 71,
                user_id: 1,
                text: 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas',
                img_attachment: 'NamDui.mov',
                timestamp: 1651802422000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 8,
        messages: [

            {
                id: 72,
                user_id: 8,
                text: 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate',
                timestamp: 1651642277000,
                status: 'read',
            },
            {
                id: 73,
                user_id: 1,
                text: 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent',
                timestamp: 1651507098000,
                status: 'read',
            },
            {
                id: 74,
                user_id: 1,
                text: 'aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae',
                img_attachment: 'MorbiQuis.mp3',
                timestamp: 1651763950000,
                status: 'read',
            },
            {
                id: 75,
                user_id: 8,
                text: 'vestibulum proin eu mi nulla ac enim',
                timestamp: 1652055829000,
                status: 'read',
            },
            {
                id: 76,
                user_id: 8,
                text: 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam',
                timestamp: 1651827209000,
                status: 'read',
            },
            {
                id: 77,
                user_id: 8,
                text: 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum',
                timestamp: 1651956862000,
                status: 'read',
            },
            {
                id: 78,
                user_id: 8,
                text: 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus',
                timestamp: 1652176640000,
                status: 'read',
            },
            {
                id: 79,
                user_id: 1,
                text: 'consequat',
                img_attachment: 'SedAccumsanFelis.xls',
                timestamp: 1651428067000,
                status: 'read',
            },
            {
                id: 80,
                user_id: 1,
                text: 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in',
                timestamp: 1651623834000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 9,
        messages: [
            {
                id: 81,
                user_id: 1,
                text: 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in',
                timestamp: 1652248979000,
                status: 'read',
            },
            {
                id: 82,
                user_id: 9,
                text: 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui',
                timestamp: 1652320783000,
                status: 'unread',
            },
            {
                id: 83,
                user_id: 9,
                text: 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices',
                timestamp: 1651860223000,
                status: 'read',
            },
            {
                id: 84,
                user_id: 1,
                text: 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci',
                img_attachment: 'OdioCondimentum.mov',
                timestamp: 1651819647000,
                status: 'read',
            },
            {
                id: 85,
                user_id: 1,
                text: 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo',
                timestamp: 1651514619000,
                status: 'read',
            },
            {
                id: 86,
                user_id: 9,
                text: 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien',
                timestamp: 1652378584000,
                status: 'unread',
            },
            {
                id: 87,
                user_id: 9,
                text: 'integer pede justo lacinia eget tincidunt eget tempus vel',
                timestamp: 1651788647000,
                status: 'read',
            },
            {
                id: 88,
                user_id: 9,
                text: 'sem mauris laoreet ut rhoncus aliquet',
                timestamp: 1652127314000,
                status: 'read',
            },
            {
                id: 89,
                user_id: 1,
                text: 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum',
                img_attachment: 'Neque.jpeg',
                timestamp: 1651792907000,
                status: 'read',
            },
            {
                id: 90,
                user_id: 1,
                text: 'non velit nec nisi',
                timestamp: 1651518156000,
                status: 'read',
            },
            {
                id: 91,
                user_id: 9,
                text: 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer',
                timestamp: 1652121819000,
                status: 'read',
            },
            {
                id: 92,
                user_id: 1,
                text: 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in',
                timestamp: 1652301177000,
                status: 'read',
            },
            {
                id: 93,
                user_id: 1,
                text: 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum',
                timestamp: 1651769110000,
                status: 'read',
            },
            {
                id: 94,
                user_id: 9,
                text: 'augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi',
                timestamp: 1651551981000,
                status: 'read',
            },
            {
                id: 95,
                user_id: 9,
                text: 'nulla neque',
                timestamp: 1652296374000,
                status: 'read',
            },
        ],
    },
    {
        user_id: 10,
        messages: [
            {
                id: 98,
                user_id: 1,
                text: 'tristique est',
                img_attachment: new URL('/static/img/attachments/attch9.jpg', import.meta.url).href,
                timestamp: 1652022278000,
                status: 'read',
            },
            {
                id: 99,
                user_id: 10,
                text: 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum',
                timestamp: 1652378684000,
                status: 'read',
            },
            {
                id: 100,
                user_id: 1,
                text: 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede',
                timestamp: 1652322542000,
                status: 'read',
            },
        ],
    },
];

export default chats;
