export const users = [
    {
        id: 1,
        first_name: 'Darcy',
        second_name: 'Dudden',
        login: 'ddudden0',
        display_name: 'Darcy Dudden',
        email: 'ddudden0@nasa.gov',
        password: '43m2IF',
        phone: '+86 (332) 522-1523',
        avatar: new URL('/static/img/avatars/av1.jpg', import.meta.url).href,
    },
    {
        id: 2,
        first_name: 'Lucy',
        second_name: 'Grzegorczyk',
        login: 'lgrzegorczyk1',
        display_name: 'Lucy Grzegorczyk',
        email: 'lgrzegorczyk1@twitter.com',
        password: 'SbMxIa',
        phone: '+507 (320) 504-0053',
        avatar: new URL('/static/img/avatars/av16.jpg', import.meta.url).href,
    },
    {
        id: 3,
        first_name: 'Fidela',
        second_name: 'Keener',
        login: 'fkeener2',
        display_name: 'Fidela Keener',
        email: 'fkeener2@dyndns.org',
        password: 'G7eiWC',
        phone: '+375 (421) 993-1303',
        avatar: new URL('/static/img/avatars/av3.jpg', import.meta.url).href,
    },
    {
        id: 4,
        first_name: 'Violette',
        second_name: 'Porritt',
        login: 'vporritt3',
        display_name: 'Violette Porritt',
        email: 'vporritt3@princeton.edu',
        password: '30fInTA',
        phone: '+48 (947) 641-0254',
        avatar: new URL('/static/img/avatars/av4.jpg', import.meta.url).href,
    },
    {
        id: 5,
        first_name: 'Tatiana',
        second_name: 'Brantl',
        login: 'tbrantl4',
        display_name: 'Tatiana Brantl',
        email: 'tbrantl4@shutterfly.com',
        password: 'LZZxX4eR7CNZ',
        phone: '+968 (538) 403-1908',
        avatar: new URL('/static/img/avatars/av10.jpg', import.meta.url).href,
    },
    {
        id: 6,
        first_name: 'Beatrisa',
        second_name: 'Garland',
        login: 'bgarland5',
        display_name: 'Beatrisa Garland',
        email: 'bgarland5@php.net',
        password: 'tJC2X0',
        phone: '+380 (210) 667-9967',
        avatar: new URL('/static/img/avatars/av6.jpg', import.meta.url).href,
    },
    {
        id: 7,
        first_name: 'Elena',
        second_name: 'Sparshutt',
        login: 'esparshutt6',
        display_name: 'Elena Sparshutt',
        email: 'esparshutt6@artisteer.com',
        password: 'O7vvOf0w3A',
        phone: '+86 (681) 781-4188',
        avatar: new URL('/static/img/avatars/av18.jpg', import.meta.url).href,
    },
    {
        id: 8,
        first_name: 'Ofelia',
        second_name: 'Thornley',
        login: 'othornley7',
        display_name: 'Ofelia Thornley',
        email: 'othornley7@wiley.com',
        password: 'QcMoSPxl',
        phone: '+420 (272) 550-8129',
        avatar: new URL('/static/img/avatars/av11.jpg', import.meta.url).href,
    },
    {
        id: 9,
        first_name: 'Flem',
        second_name: 'Chappelle',
        login: 'fchappelle8',
        display_name: 'Flem Chappelle',
        email: 'fchappelle8@123-reg.co.uk',
        password: 'ZnTbpbb3',
        phone: '+62 (817) 978-3953',
        avatar: new URL('/static/img/avatars/av9.jpg', import.meta.url).href,
    },
    {
        id: 10,
        first_name: 'Diego',
        second_name: 'Ewestace',
        login: 'dewestace9',
        display_name: 'Diego Ewestace',
        email: 'dewestace9@chicagotribune.com',
        password: 'YqVhZEiaa',
        phone: '+385 (188) 800-9242',
        avatar: new URL('/static/img/avatars/av5.jpg', import.meta.url).href,
    },
    {
        id: 11,
        first_name: 'Darnell',
        second_name: 'Labusch',
        login: 'dlabuscha',
        display_name: 'Darnell Labusch',
        email: 'dlabuscha@alexa.com',
        password: 'VUQpzY2gzQOh',
        phone: '+46 (525) 828-2476',
        avatar: new URL('/static/img/avatars/av11.jpg', import.meta.url).href,
    },
    {
        id: 12,
        first_name: 'Dominique',
        second_name: 'Jeal',
        login: 'djealb',
        display_name: 'Dominique Jeal',
        email: 'djealb@oracle.com',
        password: 'SajNUUkP',
        phone: '+86 (206) 937-5042',
        avatar: new URL('/static/img/avatars/av12.jpg', import.meta.url).href,
    },
    {
        id: 13,
        first_name: 'Audra',
        second_name: 'Trayes',
        login: 'atrayesc',
        display_name: 'Audra Trayes',
        email: 'atrayesc@craigslist.org',
        password: 'AEUsURq8p9E',
        phone: '+370 (812) 854-2778',
        avatar: new URL('/static/img/avatars/av13.jpg', import.meta.url).href,
    },
    {
        id: 14,
        first_name: 'Kaile',
        second_name: 'Cleaton',
        login: 'kcleatond',
        display_name: 'Kaile Cleaton',
        email: 'kcleatond@nymag.com',
        password: 'cAoSD0u',
        phone: '+48 (813) 785-5131',
        avatar: new URL('/static/img/avatars/av14.jpg', import.meta.url).href,
    },
    {
        id: 15,
        first_name: 'Paddie',
        second_name: 'Vasilyev',
        login: 'pvasilyeve',
        display_name: 'Paddie Vasilyev',
        email: 'pvasilyeve@imageshack.us',
        password: 'CR09gJ',
        phone: '+86 (469) 260-8788',
        avatar: new URL('/static/img/avatars/av15.jpg', import.meta.url).href,
    },
    {
        id: 16,
        first_name: 'Oralla',
        second_name: 'McNiff',
        login: 'omcnifff',
        display_name: 'Oralla McNiff',
        email: 'omcnifff@google.fr',
        password: 'GtINTNheVm',
        phone: '+33 (408) 337-3378',
        avatar: new URL('/static/img/avatars/av16.jpg', import.meta.url).href,
    },
    {
        id: 17,
        first_name: 'Maurizia',
        second_name: 'Blazewski',
        login: 'mblazewskig',
        display_name: 'Maurizia Blazewski',
        email: 'mblazewskig@cyberchimps.com',
        password: 'W1quimu8',
        phone: '+86 (826) 289-9798',
        avatar: new URL('/static/img/avatars/av17.jpg', import.meta.url).href,
    },
    {
        id: 18,
        first_name: 'Allard',
        second_name: 'Washtell',
        login: 'awashtellh',
        display_name: 'Allard Washtell',
        email: 'awashtellh@state.gov',
        password: 'kb7Gj1m7P5N',
        phone: '+1 (585) 275-4782',
        avatar: new URL('/static/img/avatars/av18.jpg', import.meta.url).href,
    },
    {
        id: 19,
        first_name: 'Edi',
        second_name: 'Redd',
        login: 'ereddi',
        display_name: 'Edi Redd',
        email: 'ereddi@wired.com',
        password: 'p3PBYO',
        phone: '+355 (927) 973-2369',
        avatar: new URL('/static/img/avatars/av19.jpg', import.meta.url).href,
    },
    {
        id: 20,
        first_name: 'Van',
        second_name: 'Skellern',
        login: 'vskellernj',
        display_name: 'Van Skellern',
        email: 'vskellernj@chron.com',
        password: '71nh2smTN',
        phone: '+62 (924) 174-3904',
        avatar: new URL('/static/img/avatars/av20.jpg', import.meta.url).href,
    },
];

export default users;
